fix

diff --git a/.github/workflows/deploy-server-with-compose.yml b/.github/workflows/deploy-server-with-compose.yml
--- a/.github/workflows/deploy-server-with-compose.yml
+++ b/.github/workflows/deploy-server-with-compose.yml
@@ -1,9 +1,8 @@
-name: deploy to ec2 with docker
+name: deply to ec2 with docker
 on:
   push:
     branches:
       - main
-
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
@@ -15,7 +14,7 @@ jobs:
         working-directory: .
         run: docker build -t hannahlee21/ordersystem:latest .
 
-      - name: dockerhub login 
+      - name: dockerhub login
         uses: docker/login-action@v1
         with:
           username: ${{secrets.DOCKER_EMAIL}}
@@ -31,9 +30,8 @@ jobs:
           username: ubuntu
           key: ${{secrets.EC2_PEMKEY}}
           script: |
-            if ! type docker > /dev/null ; then
-              sudo snap install docker || echo "docker install failed"
+            if ! type docker > /dev/null; then
+              sudo snap install docker || echo "[failed] Docker install"
             fi
             sudo docker login --username ${{secrets.DOCKER_EMAIL}} --password ${{secrets.DOCKER_PASSWORD}}
-
-            sudo docker-compose pull && sudo docker-compose up -d 
+            sudo docker-compose pull && sudo docker-compose up -d
